name: rdiary
description: "diary"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_painter: 1.0.1
  image_picker: ^1.0.7
  flex_color_picker: ^3.3.0
  intl: ^0.19.0
  uuid: ^4.0.0
  path_provider: ^2.1.2
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.0.9

  # ✅ Firebase packages compatible with Kotlin 1.8.22
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.2
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.2
  get: ^4.6.6  # Check for latest version
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"